### ISSUE TITLE
Error setting field column to true

### ISSUE THREAD

**Issue by csrui** [mboynes/super-cpt#12]
Hi, I'm testing you plugin for the first time, very nice work.

I've encountered an issue while trying to setup some fields to show up on the post list view.

Example code:

```
$eventPostType->add_meta_box( array(
    'id' => 'event-info',
    'context' => 'side',
    'fields' => array(
        'starts' => array( 'label' => __( 'Event Starts', 'my-locale' ), 'type' => 'date', 'column' => true),
        'ends' => array( 'label' => __( 'Event Ends', 'my-locale' ), 'type' => 'date'),
        'where' => array( 'label' => __( 'Where', 'my-locale' ), 'type' => 'textarea' ),
    )
) );
```

The column parameter throws an error:
Fatal error: Unsupported operand types in /.../wp-content/plugins/super-cpt/includes/class-super-custom-post-meta.php on line 678

**Comment by N-Molham** [comment]
this cause by invalid data type combination, in this line the author is joining two arrays but the initial value of $this->columns is NULL so it can't join NULL with an array, anyways you have to edit the plugin code itself to solve this by two ways.
Make the Super_Custom_Post_Meta property $columns initial value equal empty array()
OR
On the add_to_columns method of the same class check first if $this->columns is array or not

``` php
public function add_to_columns( $column ) {
    if ( !is_array($this->columns) )
        $this->columns = array();

    if ( is_array( $column ) ) {
        $this->columns = $this->columns + $column;
    }
    else {
        $this->columns[ $column ] = SCPT_Markup::labelify( $column );
    }
    $this->register_custom_columns();
}
```

**Comment by mboynes** [comment]
Funny that this bug slipped by all this time. This would only happen in cases where a label is explicitly set on a field and you add `'column' => true` to the field arguments. Apparently I've never columnized a field with an overridden label before!

Thanks for reporting it. The fix is in the master branch here, and I'll make sure it gets deployed to the plugin repo with the next version of the plugin, which should coincide with 3.6.
